### ISSUE TITLE
May I ask what parameter we should use to build index for hisat-3n

### ISSUE THREAD

**Issue by LoneKnightz** [shunliubio/eTAM-seq_workflow#2]
Hi Shun, 

I have a small question about hisat-3n index. 

At script 2, it asks for the path of hisat-3n index but it has not be mentioned at previous script. 

May I ask what parameter what should use for hisat-3n build? 
Should we just use _hisat-3n-build -p $ncpus $genome_fa $hisat3n_index_ ?
Or there is any additional parameter such as --base-change ? 

Thanks

**Comment by shunliubio** [comment]
Hi,

I always build the hisat-3n index according to its [manual ](https://daehwankimlab.github.io/hisat2/hisat-3n/). Here is one example:
```bash
hisat-3n-build -p 24 --base-change A,G --repeat-index --ss gencode.v27.ss --exon gencode.v27.exon genome.fa GRCh38_tran
```

**Comment by LoneKnightz** [comment]
Thanks!

**Comment by llecompte** [comment]
Thank you Shun.
I was wondering, in your paper, what rRNA sequence reference did you consider? How did you generate the .ss and .exon files for the rRNAs? 
`hisat-3n-build -p 24 --base-change A,G --repeat-index --ss rRNA.ss --exon rRNA.exon rRNA.fa rRNA_tran`

Best,
Lolita

**Comment by shunliubio** [comment]
Hi,

The splice site information is not needed for the rRNA case. So the options `--ss` and `--exon` are not used in the rRNA index building.

**Comment by llecompte** [comment]
Hi, 
Thank you. Which mouse rRNA sequence did you use in the paper? Did you consider each rRNA sequence as the ones annotated in the GTF or use this rRNA sequence ([Genbank BK000964.3](https://www.ncbi.nlm.nih.gov/nuccore/BK000964)), for example?
Lolita

**Comment by shunliubio** [comment]
Hi,
I used mouse rRNA sequences from NCBI. Please see the accessions below:
28S: NR_003279.1
18S: NR_003278.3
5.8S: NR_003280.2
5S: NR_030686.1
